# Site settings
name: Les Or More
email: wnarry1996@gmail.com
author: Chenlu Wang
url: https://wnarrylu.github.io/wangcl.github.io/
#resume_site: http://www.hifreud.com/Resume.io/
github: https://wnarrylu.github.io/wangcl.github.io/
baseurl: ""
description: Actually, less is more!
meta_description: AI
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: wnarrylu

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

